# Permalinks
permalink:           pretty

# Setup
title:               Matt Eding
tagline:             Python & Data Science Blog
url:                 http://matteding.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Matt Eding
  email:             matteding@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/MattEding

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
